language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - SYMFONY_DEPRECATIONS_HELPER="max[direct]=0"

branches:
    only: [master, stable]

matrix:
  fast_finish: true
  include:
    - php: nightly
      env: DEPS=dev

    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="disabled=1"

    - php: 7.3
      env: SYMFONY_REQUIRE="3.*"

    - php: 7.3
      env: SYMFONY_REQUIRE="4.*"

  allow_failures:
    - php: nightly

before_install:
  - set -eo pipefail
  - phpenv config-rm xdebug.ini || true
  - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
  - if [ "$DEPS" != "" ]; then perl -pi -e "s/^}\$/,\"minimum-stability\":\"$DEPS\"}/" composer.json; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: ./vendor/bin/simple-phpunit
